apiVersion: v1
kind: Service
metadata:
  name: backend2-api-service
  namespace: "{{ .Values.namespace }}"
spec:
  selector:
    app: backend2-api
  type: ClusterIP
  # clusterIP: None
  ports:
    - name: backend2-api
      port: 80
      targetPort: 8000
      protocol: TCP
