# Default values for backend2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: backend2
hosts:
  - nitechregular.sukruthgrandhi.com
  - sukruthgrandhi.com

image:
  repository: localhost:32000/backend2
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

envVariables:
  - name: DB_USER
    value: root
  - name: DB_PASSWORD
    value: nitest
  - name: DB_HOST
    value: dashboard-nib6-uat.ni.systems
  - name: DB_PORT
    value: "3306"
  - name: DB_NAME
    value: test
  - name: secret
    value: 387613b80adfa6e333d9ffbaeb5dcfc4
  - name: algorithm
    value: HS256
  - name: BACKEND2_URL
    value: http://localhost:8000
